defaults: &defaults
    docker:
        - image: circleci/node:8

version: 2
jobs:
    prepare:
        <<: *defaults
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
            - run: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - persist_to_workspace:
                  root: .
                  paths:
                      - node_modules
    build:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run: npm run build
            - persist_to_workspace:
                  root: .
                  paths:
                      - build
    tu:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run: npm run test
